export const CREATE_CHAT = "CREATE_CHAT";
export const CREATE_GROUP = "CREATE_GROUP";
export const GET_ALL_CHATS = "GET_ALL_CHATS";
export const DELETE_CHAT = "DELETE_CHAT";
export const ADD_MEMBER_TO_GROUP = "ADD_MEMBER_TO_GROUP";
export const REMOVE_MEMBER_FROM_GROUP = "REMOVE_MEMBER_FROM_GROUP";